package Model;

import java.time.LocalDate;
import java.time.LocalTime;

/**Manages Appointment objects within program. */
public class Appointment {

    private int appointmentID;
    private String title;
    private String description;
    private String location;
    private int customerID;
    private int contactID;
    private String type;
    private LocalDate startDate;
    private LocalTime startTime;
    private LocalDate endDate;
    private LocalTime endTime;

    /**Appointment class constructor.
     * @param appointmentID int autogenerated ID.
     * @param title String appointment title.
     * @param description appointment description.
     * @param location String appointment location.
     * @param customerID int customer ID for PK/FK.
     * @param contactID int contact ID for PK/FK.
     * @param type String appointment type.
     * @param startDate LocalDate appointment start day.
     * @param startTime LocalTime appointment start time.
     * @param endDate LocalDate appointment end day.
     * @param endTime LocalTime appointment end time. */
    public Appointment(int appointmentID, String title, String description, String location, int customerID,
                       int contactID, String type, LocalDate startDate, LocalTime startTime, LocalDate endDate,
                       LocalTime endTime) {
        this.appointmentID = appointmentID;
        this.title = title;
        this.description = description;
        this.location = location;
        this.customerID = customerID;
        this.contactID = contactID;
        this.type = type;
        this.startDate = startDate;
        this.startTime = startTime;
        this.endDate = endDate;
        this.endTime = endTime;
    }

    /**Get appointment ID.
     * @return this.appointmentID. */
    public int getAppointmentID() {
        return appointmentID;
    }

    /**Set appointment ID.
     * @param appointmentID int. */
    public void setAppointmentID(int appointmentID) {
        this.appointmentID = appointmentID;
    }

    /**Get appointment title.
     * @return this.title. */
    public String getTitle() {
        return title;
    }

    /**Set appointment title.
     * @param title String. */
    public void setTitle(String title) {
        this.title = title;
    }

    /**Get appointment description.
     * @return this.description. */
    public String getDescription() {
        return description;
    }

    /**Set appointment description.
     * @param description String. */
    public void setDescription(String description) {
        this.description = description;
    }

    /**Get appointment location.
     * @return this.location. */
    public String getLocation() {
        return location;
    }

    /**Set appointment location.
     * @param location String. */
    public void setLocation(String location) {
        this.location = location;
    }

    /**Get appointment customer ID.
     * @return this.customerID. */
    public int getCustomerID() {
        return customerID;
    }

    /**Set appointment customer ID.
     * @param customerID int. */
    public void setCustomerID(int customerID) {
        this.customerID = customerID;
    }

    /**Get appointment contact ID.
     * @return this.contactID. */
    public int getContactID() {
        return contactID;
    }

    /**Set appointment contact ID.
     * @param contactID int. */
    public void setContactID(int contactID) {
        this.contactID = contactID;
    }

    /**Get appointment type.
     * @return this.type. */
    public String getType() {
        return type;
    }

    /**Set appointment type.
     * @param type String. */
    public void setType(String type) {
        this.type = type;
    }

    /**Get appointment start day.
     * @return this.startDate. */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**Set appointment start day.
     * @param startDate LocalDate. */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**Get appointment start time.
     * @return this.startTime. */
    public LocalTime getStartTime() {
        return startTime;
    }

    /**Set appointment start time.
     * @param startTime LocalTime. */
    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    /**Get appointment end day.
     * @return this.endDate. */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**Set appointment end day.
     * @param endDate LocalDate. */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**Get appointment end time.
     * @return this.endTime. */
    public LocalTime getEndTime() {
        return endTime;
    }

    /**Set appointment end time.
     * @param endTime LocalTime. */
    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }
}
